# Generated by Django 5.0.6 on 2024-07-06 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoqueitens_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocoloentrega',
            name='data_retorno',
        ),
        migrations.RemoveField(
            model_name='protocoloentrega',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='protocoloentrega',
            name='estoque_retornado',
        ),
        migrations.AlterField(
            model_name='protocoloentregaitens',
            name='protocolo_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolo_entrega_itens', to='estoque.protocoloentrega'),
        ),
    ]
